---
version: "3"
services:
  ceos:
    container_name: ceos-institucional
    build:
      context: ./
    image: ceosjr/institucional:latest
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    volumes:
      - webroot:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - ceos
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
