version: "3"
services:
  ceos:
    container_name: ceos-institucional
    build:
      context: ./
    image: ceos-institucional:latest
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    image: nginx-dus-guri:latest
    depends_on:
      - ceos
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
