---
version: "3"
services:
  ceos:
    container_name: ceos-institucional
    build:
      context: ./
    image: ceosjr/institucional:latest
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - ceos
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email  ceos.adm@gmail.com --agree-tos --no-eff-email --staging -d ceos.dc.ufc.br
